---
server-url: "http://localhost:8080"
application-id: "pvENvlYCXGv"
application-info:
  license:
    source: "LICENSE"
    target: "LICENSE"
    executable: false
  exe-name: "ignite"
  supported-operating-systems:
  - "linux"
  - "mac"
  - "windows"
