---
server-url: "http://localhost:8080"
application-id: "pvENvlYCXGv"
application-info:
  license:
    source: "LICENSE"
    target: "LICENSE"
    executable: false
  splash-screen:
    source: "resources/ignite-splash-screen.png"
    target: "splash.png"
    executable: false
  exe-name: "ignite"
  supported-operating-systems:
  - "windows"
  - "mac"
  - "linux"
